teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - christinaharter
      - minyu66
      - thelinuxfoundation
  - name: nightstream-maintainers
    maintainers:
      - SebastienGllmt
      - nicarq
    members:
      - rvcas
      - L-as
      - ecioppettini
      - SpaceManiac
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      nightstream-maintainers: maintain
    visibility: public
  - name: Starstream
    teams:
      nightstream-maintainers: maintain
    visibility: public
